package eu.sisik.backgroundcam.util

object Constants {
    const val REQUEST_CODE_ACTIVITY_TRANSITION = 123
    const val REQUEST_CODE_INTENT_ACTIVITY_TRANSITION = 122
    const val ACTIVITY_TRANSITION_NOTIFICATION_ID = 111
    const val ALERT_MODE_SELECTION = "ALERT_MODE_SELECTION"
    const val SNOOZE_SELECTION = "SNOOZE_SELECTION"
}